# Generated by Django 3.0.3 on 2020-07-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200708_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='audio',
            field=models.FileField(null=True, upload_to='audio_files', verbose_name=''),
        ),
    ]
